package ru.itmo.wp.model.repository.impl;

import ru.itmo.wp.model.database.DatabaseUtils;
import ru.itmo.wp.model.exception.RepositoryException;
import ru.itmo.wp.model.repository.Setter;

import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public abstract class AbstractRepository<T> {
    private final DataSource DATA_SOURCE = DatabaseUtils.getDataSource();

    public void save(T entity, String SQLRequest, Setter<T, PreparedStatement> statementSetter, Setter<T, ResultSet> entitySetter) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement(SQLRequest, Statement.RETURN_GENERATED_KEYS)) {
                statementSetter.set(entity, statement);
                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save " + entity.getClass() + ".");
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        entitySetter.set(entity, generatedKeys);
                    } else {
                        throw new RepositoryException("Can't save" + entity.getClass() + "[no autogenerated fields].");
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save " + entity.getClass() + ".", e);
        }
    }

    public T findBy(T entity, String SQLRequest, Setter<T, PreparedStatement> statementSetter) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement(SQLRequest)) {
                statementSetter.set(entity, statement);
                try (ResultSet resultSet = statement.executeQuery()) {
                    return toEntity(statement.getMetaData(), resultSet);
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find Event.", e);
        }
    }

    public List<T> findAll(String SQLRequest) {
        List<T> entities = new ArrayList<>();
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement(SQLRequest)) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    T entity;
                    while ((entity = toEntity(statement.getMetaData(), resultSet)) != null) {
                        entities.add(entity);
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find.", e);
        }
        return entities;
    }

    protected abstract T toEntity(ResultSetMetaData metaData, ResultSet resultSet) throws SQLException;

}
